### ISSUE TITLE
command 'sortAlphabetically' not found

### ISSUE THREAD

**Issue by AgustinVignoli** [AvraamMavridis/vsc-sort-react#1]
I got this error: "command 'sortAlphabetically' not found" when trying to run the command.
I'm using the very last version of VS Code

**Comment by AvraamMavridis** [comment]
@AgustinVignoli it should be solved in 1.3.0. Thx! https://github.com/AvraamMavridis/vsc-sort-react/commit/a6a5bbe922e1e245a0cdb2bf633698d0049a3b10
